for var in NEXT_PUBLIC_CLIENT_BASE_URL API_KEY_FIREBASE AUTH_DOMAIN_FIREBASE PROJECT_ID_FIREBASE STORAGE_BUCKET MESSAGING_SENDER_ID APP_ID ENGLISH_CODE KHMER_CODE CLIENT_ID ABA_PAY_WAY_SCRIPT ABA_PAY_WAY_STYLE BASE_URL FACEBOOK_APP GA_TRACKING_ID SOCKET_URL GOOGLE_API_KEY ABA_PAYWAY_PLUGIN; do
  printenv | grep "^$var" >>.env
done
