name: deployment

#event 
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs: 
  build: 
    runs-on: ${{matrix.os}}

    strategy: 
      matrix: 
        node-version: [10.x , 14.x, 16.x]
        os: [macos-latest, window-latest, ubuntu-18.04]
    steps:
      - uses: actions/checkout@v1
      - uses: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with: 
          node_version: ${{matrix.node-version}}
      - name: yarn , build and test
        run: 
          yarn 
          yarn build --if-present
        env: 
          CI: true
